services:
  tg-sender:
    container_name: tg-sender
    hostname: tg-sender
    image: tg-sender
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "${VERSION}"
        GIT_COMMIT: "${COMMIT_HASH}"
        BUILD_TIME: "${BUILD_TIME}"
    environment:
      - CONFIG_PATH=/app/data/config.yaml
    volumes:
      - ./config/config.yaml:/app/data/config.yaml
    networks:
      - tgqueue_default
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  tgqueue_default:
    external: true
