env: "local"
amqp:
  host: "rabbitmq"
  port: 5672
  queue: tg-sender-queue
  exchange: test-ex
  routing_key: test-key
otlp_config:
  host: "jaeger"
  port: 4317
  service_name: "tg-sender"
tg_config:
  base_url: http://telegram-bot-api:8381
  token: ""